# Generated by Django 5.2 on 2025-04-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_slug_alter_offer_base_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='subject',
            field=models.CharField(default='New Thread', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('engineer', 'Engineer')], default='client', max_length=10),
        ),
    ]
