# Generated by Django 4.2.21 on 2025-05-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('engineer', 'Engineer'), ('songwriter', 'Songwriter'), ('producer', 'Producer'), ('mixer', 'Mixer')], default='client', max_length=10),
        ),
    ]
